# Number of days of inactivity before an issue becomes stale
daysUntilStale: 15
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 15
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - needs discussion
  - in progress
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale by StaleBOT because it has not had any
  recent activity. It will be closed if no further activity occurs in 15 days. Thank you all
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
